/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author adi50
 */
public class FormNav extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormNav
     */
    public FormNav() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butInData = new javax.swing.JButton();
        butShowData = new javax.swing.JButton();

        butInData.setText("Masukan data");
        butInData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInDataActionPerformed(evt);
            }
        });

        butShowData.setText("Tampilkan data");
        butShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butShowDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(butInData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(butShowData)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butInData)
                    .addComponent(butShowData))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butShowDataActionPerformed
        
      
        
    }//GEN-LAST:event_butShowDataActionPerformed

    private void butInDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInDataActionPerformed

          
          InputDataForm id = new InputDataForm();
          id.setVisible(true);
          this.getDesktopPane().add(id);
          this.dispose();
        
    }//GEN-LAST:event_butInDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butInData;
    private javax.swing.JButton butShowData;
    // End of variables declaration//GEN-END:variables
}
